### ISSUE TITLE
A way to add new keybinds

### ISSUE THREAD

**Issue by raphydaphy** [RockBottomGame/API#8]
At the moment there is no official way to add keybinds and therefore any keys we add don't show up on the controls screen. It would be great if we had a method to add a configurable key to that screen so that users know the key to press and are able to change it easily.

**Comment by raphydaphy** [comment]
didnt u add this in 0.11 lol ?

**Comment by Ellpeck** [comment]
No?

**Comment by raphydaphy** [comment]
apparently not
